In [59]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes  import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.metrics import accuracy_score

In [60]:
df = pd.read_csv("train.txt",sep=";",header=None,names=["text","emotion"])
df.head()

                                                text  emotion
0                            I didnt feel humiliated  sadness
1  I can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [61]:
df.shape

(16000, 2)

In [62]:
df.columns

Index(['text', 'emotion'], dtype='object')

In [63]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [64]:
df.drop_duplicates()

                                                    text  emotion
0                                I didnt feel humiliated  sadness
1      I can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[15999 rows x 2 columns]

In [65]:
lab_enco = LabelEncoder()
df["emotion"] = lab_enco.fit_transform(df["emotion"])
df.head()

                                                text  emotion
0                            I didnt feel humiliated        4
1  I can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [66]:
df["emotion"].unique()

array([4, 0, 3, 5, 1, 2])

In [67]:
df["text"] = df["text"].apply(lambda X:X.lower())
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [68]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans("","",string.punctuation))

df["text"] = df["text"].apply(remove_punc)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [69]:
def remove_number(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new+i
    return new
df["text"] = df["text"].apply(remove_number)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [70]:
def remove_enojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new+=i
    return new

df["text"] = df["text"].apply(remove_enojis)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [71]:
from nltk.corpus import stopwords
s_w = set(stopwords.words("english"))
s_w

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [72]:
def remove_stopwords(txt):
    words_list = txt.split()
    cleaned = []
    for i in words_list:
        if not i in s_w:
            cleaned.append(i)
    return ' '.join(cleaned)

df["text"] = df["text"].apply(remove_stopwords)
df.loc[1]["text"]

'go feeling hopeless damned hopeful around someone cares awake'

In [73]:
X = df["text"]
y = df["emotion"]

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
Count_Vectorizer = CountVectorizer()
Tfidf_Vectorizer = TfidfVectorizer()

X_train_Count = Count_Vectorizer.fit_transform(X_train)
X_test_Count = Count_Vectorizer.fit_transform(X_test)
X_train_Tfidf = Tfidf_Vectorizer.transform(X_train)
X_test_Tfidf = Tfidf_Vectorizer.transform(X_test)

In [ ]:
models = {
    "nb2":MultinomialNB(),
    "LR":LogisticRegression()
}

# X_trains = {
#     "X_train_Count":X_train_Count,
#     "X_train_Tfidf":X_train_Tfidf
# }
# for name,model in models.items():
#     for X_,X_tr in X_trains.items():
#         if X_ == "X_train_Count":
#             model.fit(X_tr,y_train)
#             y_pred = model.predict(X_test_Count)
#             print(f"{name} : {X_}",accuracy_score(y_test,y_pred))
#         else:
#             model.fit(X_tr,y_train)
#             y_pred = model.predict(X_test_Tfidf)
#             print(f"{name} : {X_}",accuracy_score(y_test,y_pred))


for name,model in models.items():
    model.fit(X_test_Count,y_train)
    y_pred = model.predict(X_test_Count)
    print(f"{name} : X_test_Count",accuracy_score(y_test,y_pred))
for name,model in models.items():
    model.fit(X_test_Tfidf,y_train)
    y_pred = model.predict(X_test_Tfidf)
    print(f"{name} : X_test_Tfidf",accuracy_score(y_test,y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [3200, 12800]